auth:
  openid:
    enabled: true
    redirecturl: http://vikunja.playground.dev:9030/auth/openid/
    providers:
      keycloak:
        name: Keycloak
        authurl: https://keycloak.playground.dev:8081/realms/playground
        logouturl: https://keycloak.playground.dev:8081/realms/playground/protocol/openid-connect/logout
        clientid: vikunja
        clientsecret: vikunja-secret