profile:
    path: /profile
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        path: '%frontend-host%/profile'
        permanent: false

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
